"""Agregar campo razon_social en proveedor

Revision ID: 4911252ef21b
Revises: 645df1c2f4e5
Create Date: 2025-07-23 09:43:05.705963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4911252ef21b'
down_revision: Union[str, Sequence[str], None] = '645df1c2f4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedores', sa.Column('razon_social', sa.String(), nullable=True))
    op.add_column('proveedores', sa.Column('clave_sii', sa.String(), nullable=True))
    op.add_column('proveedores', sa.Column('cookies_sii_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proveedores', 'cookies_sii_path')
    op.drop_column('proveedores', 'clave_sii')
    op.drop_column('proveedores', 'razon_social')
    # ### end Alembic commands ###
