"""add estado to ofertas_financiamiento

Revision ID: 6028555466fe
Revises: 9be1c641eae3
Create Date: 2025-07-11 12:47:33.495923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6028555466fe'
down_revision: Union[str, Sequence[str], None] = '9be1c641eae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_condiciones_por_pagador_id'), table_name='condiciones_por_pagador')
    op.drop_table('condiciones_por_pagador')
    op.drop_index(op.f('ix_facturas_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_rut_emisor'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_financiadores_id'), table_name='financiadores')
    op.drop_index(op.f('ix_financiadores_usuario'), table_name='financiadores')
    op.drop_table('financiadores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_rut'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_usuario'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_ofertas_financiamiento_id'), table_name='ofertas_financiamiento')
    op.drop_table('ofertas_financiamiento')
    op.drop_index(op.f('ix_pagadores_id'), table_name='pagadores')
    op.drop_index(op.f('ix_pagadores_rut'), table_name='pagadores')
    op.drop_index(op.f('ix_pagadores_usuario'), table_name='pagadores')
    op.drop_table('pagadores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagadores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=False),
    sa.Column('rut', sa.VARCHAR(), nullable=False),
    sa.Column('usuario', sa.VARCHAR(), nullable=False),
    sa.Column('clave_hash', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagadores_usuario'), 'pagadores', ['usuario'], unique=1)
    op.create_index(op.f('ix_pagadores_rut'), 'pagadores', ['rut'], unique=1)
    op.create_index(op.f('ix_pagadores_id'), 'pagadores', ['id'], unique=False)
    op.create_table('ofertas_financiamiento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tasa_interes', sa.FLOAT(), nullable=True),
    sa.Column('dias_anticipacion', sa.INTEGER(), nullable=True),
    sa.Column('monto_total', sa.FLOAT(), nullable=True),
    sa.Column('factura_id', sa.INTEGER(), nullable=True),
    sa.Column('financiador_id', sa.INTEGER(), nullable=True),
    sa.Column('comision_flat', sa.FLOAT(), nullable=True),
    sa.Column('precio_cesion', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['financiador_id'], ['financiadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ofertas_financiamiento_id'), 'ofertas_financiamiento', ['id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=False),
    sa.Column('rut', sa.VARCHAR(), nullable=False),
    sa.Column('usuario', sa.VARCHAR(), nullable=False),
    sa.Column('clave_hash', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_usuario'), 'proveedores', ['usuario'], unique=1)
    op.create_index(op.f('ix_proveedores_rut'), 'proveedores', ['rut'], unique=1)
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_table('financiadores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=False),
    sa.Column('usuario', sa.VARCHAR(), nullable=False),
    sa.Column('clave_hash', sa.VARCHAR(), nullable=False),
    sa.Column('costo_fondos', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financiadores_usuario'), 'financiadores', ['usuario'], unique=1)
    op.create_index(op.f('ix_financiadores_id'), 'financiadores', ['id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rut_emisor', sa.VARCHAR(), nullable=True),
    sa.Column('rut_receptor', sa.VARCHAR(), nullable=True),
    sa.Column('tipo_dte', sa.VARCHAR(), nullable=True),
    sa.Column('folio', sa.INTEGER(), nullable=True),
    sa.Column('monto', sa.INTEGER(), nullable=True),
    sa.Column('estado_dte', sa.VARCHAR(), nullable=True),
    sa.Column('razon_social_emisor', sa.VARCHAR(), nullable=True),
    sa.Column('razon_social_receptor', sa.VARCHAR(), nullable=True),
    sa.Column('fecha_emision', sa.DATE(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=True),
    sa.Column('fecha_vencimiento_original', sa.DATE(), nullable=True),
    sa.Column('modificacion_aceptada_por_proveedor', sa.BOOLEAN(), nullable=True),
    sa.Column('confirming_solicitado', sa.BOOLEAN(), nullable=True),
    sa.Column('origen_confirmacion', sa.VARCHAR(), nullable=True),
    sa.Column('financiador_adjudicado', sa.VARCHAR(), nullable=True),
    sa.Column('proveedor_id', sa.INTEGER(), nullable=True),
    sa.Column('pagador_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pagador_id'], ['pagadores.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_rut_emisor'), 'facturas', ['rut_emisor'], unique=False)
    op.create_index(op.f('ix_facturas_id'), 'facturas', ['id'], unique=False)
    op.create_table('condiciones_por_pagador',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('financiador_id', sa.INTEGER(), nullable=False),
    sa.Column('rut_pagador', sa.VARCHAR(), nullable=False),
    sa.Column('nombre_pagador', sa.VARCHAR(), nullable=False),
    sa.Column('spread', sa.FLOAT(), nullable=True),
    sa.Column('dias_anticipacion', sa.INTEGER(), nullable=True),
    sa.Column('comisiones', sa.FLOAT(), nullable=True),
    sa.Column('nombre_financiador', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['financiador_id'], ['financiadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condiciones_por_pagador_id'), 'condiciones_por_pagador', ['id'], unique=False)
    # ### end Alembic commands ###
