"""add fecha_recepcion to facturas

Revision ID: 760ad6898391
Revises: f9f186ac6de3
Create Date: 2025-08-12 11:32:33.664076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760ad6898391'
down_revision: Union[str, Sequence[str], None] = 'f9f186ac6de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('fecha_recepcion', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'fecha_recepcion')
    # ### end Alembic commands ###
