"""Agregar campos extra para facturas desde SII

Revision ID: 8586994d5678
Revises: 4911252ef21b
Create Date: 2025-08-01 09:44:12.207982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8586994d5678'
down_revision: Union[str, Sequence[str], None] = '4911252ef21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('dias_desde_emision', sa.Integer(), nullable=True))
    op.add_column('facturas', sa.Column('detEventoReceptor', sa.String(), nullable=True))
    op.add_column('facturas', sa.Column('detEventoReceptorLeyenda', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'detEventoReceptorLeyenda')
    op.drop_column('facturas', 'detEventoReceptor')
    op.drop_column('facturas', 'dias_desde_emision')
    # ### end Alembic commands ###
