"""Base limpia

Revision ID: bfcd54a3a1aa
Revises: 
Create Date: 2025-07-18 16:11:42.713605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfcd54a3a1aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fondos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fondos_id'), 'fondos', ['id'], unique=False)
    op.create_table('pagadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('clave_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagadores_id'), 'pagadores', ['id'], unique=False)
    op.create_index(op.f('ix_pagadores_rut'), 'pagadores', ['rut'], unique=True)
    op.create_index(op.f('ix_pagadores_usuario'), 'pagadores', ['usuario'], unique=True)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('clave_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_rut'), 'proveedores', ['rut'], unique=True)
    op.create_index(op.f('ix_proveedores_usuario'), 'proveedores', ['usuario'], unique=True)
    op.create_table('financiadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('clave_hash', sa.String(), nullable=False),
    sa.Column('fondo_id', sa.Integer(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.Column('costo_fondos_mensual', sa.Float(), nullable=True),
    sa.Column('fecha_costo_fondos', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['fondo_id'], ['fondos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financiadores_id'), 'financiadores', ['id'], unique=False)
    op.create_index(op.f('ix_financiadores_usuario'), 'financiadores', ['usuario'], unique=True)
    op.create_table('condiciones_por_pagador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financiador_id', sa.Integer(), nullable=False),
    sa.Column('rut_pagador', sa.String(), nullable=False),
    sa.Column('nombre_pagador', sa.String(), nullable=False),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('dias_anticipacion', sa.Integer(), nullable=True),
    sa.Column('comisiones', sa.Float(), nullable=True),
    sa.Column('nombre_financiador', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['financiador_id'], ['financiadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condiciones_por_pagador_id'), 'condiciones_por_pagador', ['id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut_emisor', sa.String(), nullable=True),
    sa.Column('rut_receptor', sa.String(), nullable=True),
    sa.Column('tipo_dte', sa.String(), nullable=True),
    sa.Column('folio', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Integer(), nullable=True),
    sa.Column('estado_dte', sa.String(), nullable=True),
    sa.Column('razon_social_emisor', sa.String(), nullable=True),
    sa.Column('razon_social_receptor', sa.String(), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento_original', sa.Date(), nullable=True),
    sa.Column('modificacion_aceptada_por_proveedor', sa.Boolean(), nullable=True),
    sa.Column('confirming_solicitado', sa.Boolean(), nullable=True),
    sa.Column('origen_confirmacion', sa.String(), nullable=True),
    sa.Column('financiador_adjudicado', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('pagador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['financiador_adjudicado'], ['financiadores.id'], ),
    sa.ForeignKeyConstraint(['pagador_id'], ['pagadores.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_id'), 'facturas', ['id'], unique=False)
    op.create_index(op.f('ix_facturas_rut_emisor'), 'facturas', ['rut_emisor'], unique=False)
    op.create_table('ofertas_financiamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasa_interes', sa.Float(), nullable=True),
    sa.Column('dias_anticipacion', sa.Integer(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('comision_flat', sa.Float(), nullable=True),
    sa.Column('precio_cesion', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('factura_id', sa.Integer(), nullable=True),
    sa.Column('financiador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['financiador_id'], ['financiadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ofertas_financiamiento_id'), 'ofertas_financiamiento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ofertas_financiamiento_id'), table_name='ofertas_financiamiento')
    op.drop_table('ofertas_financiamiento')
    op.drop_index(op.f('ix_facturas_rut_emisor'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_id'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_condiciones_por_pagador_id'), table_name='condiciones_por_pagador')
    op.drop_table('condiciones_por_pagador')
    op.drop_index(op.f('ix_financiadores_usuario'), table_name='financiadores')
    op.drop_index(op.f('ix_financiadores_id'), table_name='financiadores')
    op.drop_table('financiadores')
    op.drop_index(op.f('ix_proveedores_usuario'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_rut'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_pagadores_usuario'), table_name='pagadores')
    op.drop_index(op.f('ix_pagadores_rut'), table_name='pagadores')
    op.drop_index(op.f('ix_pagadores_id'), table_name='pagadores')
    op.drop_table('pagadores')
    op.drop_index(op.f('ix_fondos_id'), table_name='fondos')
    op.drop_table('fondos')
    # ### end Alembic commands ###
