"""add ESG tables

Revision ID: cfa082af7250
Revises: 1e4afb1c9b0a
Create Date: 2025-08-20 14:55:28.728326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa082af7250'
down_revision: Union[str, Sequence[str], None] = '1e4afb1c9b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_criterios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=1), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('answer_type', sa.String(length=20), nullable=True),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_esg_criterios_id'), 'esg_criterios', ['id'], unique=False)
    op.create_table('esg_evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_rut', sa.String(length=20), nullable=False),
    sa.Column('periodo_anio', sa.Integer(), nullable=False),
    sa.Column('periodo_mes', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('puntaje_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_evaluaciones_proveedor_rut'), 'esg_evaluaciones', ['proveedor_rut'], unique=False)
    op.create_table('esg_evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('criterio_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['esg_evaluaciones.id'], ),
    sa.ForeignKeyConstraint(['criterio_id'], ['esg_criterios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_evidencias_assessment_id'), 'esg_evidencias', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_esg_evidencias_criterio_id'), 'esg_evidencias', ['criterio_id'], unique=False)
    op.create_table('esg_respuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('criterio_id', sa.Integer(), nullable=False),
    sa.Column('valor_bool', sa.Boolean(), nullable=True),
    sa.Column('valor_number', sa.Float(), nullable=True),
    sa.Column('valor_text', sa.Text(), nullable=True),
    sa.Column('evidencia_url', sa.String(length=500), nullable=True),
    sa.Column('puntaje', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['esg_evaluaciones.id'], ),
    sa.ForeignKeyConstraint(['criterio_id'], ['esg_criterios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'criterio_id', name='uq_assessment_criterio')
    )
    op.create_index(op.f('ix_esg_respuestas_assessment_id'), 'esg_respuestas', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_esg_respuestas_criterio_id'), 'esg_respuestas', ['criterio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esg_respuestas_criterio_id'), table_name='esg_respuestas')
    op.drop_index(op.f('ix_esg_respuestas_assessment_id'), table_name='esg_respuestas')
    op.drop_table('esg_respuestas')
    op.drop_index(op.f('ix_esg_evidencias_criterio_id'), table_name='esg_evidencias')
    op.drop_index(op.f('ix_esg_evidencias_assessment_id'), table_name='esg_evidencias')
    op.drop_table('esg_evidencias')
    op.drop_index(op.f('ix_esg_evaluaciones_proveedor_rut'), table_name='esg_evaluaciones')
    op.drop_table('esg_evaluaciones')
    op.drop_index(op.f('ix_esg_criterios_id'), table_name='esg_criterios')
    op.drop_table('esg_criterios')
    # ### end Alembic commands ###
