"""add fecha_confirmacion to facturas

Revision ID: d556f442cc96
Revises: db32a70a464c
Create Date: 2025-08-09 14:36:51.014707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd556f442cc96'
down_revision: Union[str, Sequence[str], None] = 'db32a70a464c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('fecha_confirmacion', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'fecha_confirmacion')
    # ### end Alembic commands ###
